adminUser:
  password: vault:leopardgentle/adminUser:password
  username: admin
dashboardAuthID: vault:leopardgentle:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:leopardgentle:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:leopardgentle/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:leopardgentle/prow:hmacToken
